# Generated by Django 5.0.6 on 2024-07-04 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('resistance', models.FloatField(blank=True, help_text='Resistance in kg', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('muscle_group', models.CharField(blank=True, choices=[('upper', 'Upper Body'), ('lower', 'Lower Body'), ('core', 'Core'), ('full', 'Full Body')], max_length=100)),
                ('is_cardio', models.BooleanField(default=False, help_text='Czy ćwiczenie jest cardio?')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excercises', to='you_train_api.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='you_train_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='ExcerciseInSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField(blank=True, default=1, verbose_name='Ile powtórzeń')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Długość ćwiczenia')),
                ('rest_time', models.DurationField(blank=True, help_text='Czas odpoczynku między seriami', null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='you_train_api.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='you_train_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cyclic', models.BooleanField(default=False, help_text='Czy powtarza się co tydzień?')),
                ('cycle_length', models.IntegerField(default=1, help_text='Ile tygodni ma trwać Plan?')),
                ('training_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plan', to='you_train_api.trainingplan')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='you_train_api.workoutplan')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField(verbose_name='Ile razy blok ma być powtórzony')),
                ('rest_time', models.DurationField(help_text='Czas odpoczynku między seriami')),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('excercises', models.ManyToManyField(through='you_train_api.ExcerciseInSegment', to='you_train_api.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seggments', to='you_train_api.workout')),
            ],
        ),
        migrations.AddField(
            model_name='excerciseinsegment',
            name='workout_segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='you_train_api.workoutsegment'),
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=300)),
                ('date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='you_train_api.workout')),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='you_train_api.workoutplan')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=300)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('avg_heart_rate', models.IntegerField(blank=True, null=True)),
                ('max_heart_rate', models.IntegerField(blank=True, null=True)),
                ('satisfaction', models.IntegerField(blank=True, null=True)),
                ('well_being', models.IntegerField(blank=True, null=True)),
                ('workout_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='you_train_api.workoutsession')),
            ],
        ),
    ]
