# Generated by Django 5.0.6 on 2024-07-20 09:34

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("you_train_api", "0002_alter_workoutplan_cycle_length_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ExcerciseInSegment",
            new_name="ExerciseInSegment",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="day_of_week",
        ),
        migrations.RemoveField(
            model_name="workoutsegment",
            name="excercises",
        ),
        migrations.AddField(
            model_name="workout",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workoutsegment",
            name="exercises",
            field=models.ManyToManyField(
                through="you_train_api.ExerciseInSegment", to="you_train_api.exercise"
            ),
        ),
        migrations.RemoveField(
            model_name="workout",
            name="workout_plan",
        ),
        migrations.AlterField(
            model_name="workoutplan",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 20, 9, 33, 39, 517074, tzinfo=datetime.timezone.utc
                ),
                help_text="Data rozpoczęcia planu",
            ),
        ),
        migrations.CreateModel(
            name="WorkoutInPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="you_train_api.workout",
                    ),
                ),
                (
                    "workout_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="you_train_api.workoutplan",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="workout",
            name="workout_plan",
            field=models.ManyToManyField(
                through="you_train_api.WorkoutInPlan", to="you_train_api.workoutplan"
            ),
        ),
    ]
