# Generated by Django 5.0.6 on 2024-07-27 09:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('you_train_api', '0003_rename_excerciseinsegment_exerciseinsegment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 27, 9, 15, 14, 849516, tzinfo=datetime.timezone.utc), help_text='Data rozpoczęcia planu'),
        ),
        migrations.AlterField(
            model_name='workoutsegment',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='you_train_api.workout'),
        ),
    ]
