# Generated by Django 5.0.6 on 2024-08-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("you_train_api", "0005_alter_workoutplan_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutinplan",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
