# Generated by Django 5.0.6 on 2024-08-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("you_train_api", "0006_workoutinplan_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutsegment",
            name="rest_time",
            field=models.DurationField(
                blank=True, help_text="Czas odpoczynku między seriami", null=True
            ),
        ),
    ]
